
[build]
  publish = "client/dist"  # Adjust this path as necessary for your build output
  command = "npm run build" # Command to build the project

[dev]
  command = "npm run dev"    # Command to start the development server
  port = 3000                 # Port for local development

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
